name: Build static files and deploy staging
on:
  push:
    branches:
      - develop
jobs:
  build-and-staging:
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Prepare staging ğŸ”§
        run: |
          .scripts/run deploy:staging

      - name: Deploy to gh-pages for staging ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: staging-readonly
          folder: dist
