name: Build static files and deploy staging
on:
  push:
    branches:
      - develop
jobs:
  build-and-staging:
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install deps ğŸ”§
        run: |
          yarn install

      - name: Build and remove debugging dependencies ğŸ”§
        run: |
          yarn ci:build

      - name: Move HTML to dist ğŸ”§
        run: |
          mv ./infrastructure/ui/staging.html ./dist/index.html

      - name: Deploy to gh-pages for staging ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: staging-readonly
          folder: dist
